name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build
        run: gradle build -Pcommit=${{ github.sha }}

      - name: Upload build results
        uses: actions/upload-artifact@v7
        with:
          name: Release Build
          path: ${{ github.workspace }}/build/libs/
          if-no-files-found: error
          retention-days: 14
